version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: course_platform_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-course_platform}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - course_platform

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: course_platform_pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeMe123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - course_platform

networks:
  course_platform:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: